### ISSUE TITLE
Parsing form data

### ISSUE THREAD

**Issue by janfri** [rack-app/rack-app#10]
Is there a nice way to get parsed values of form data? I can do

``` ruby
class App < RackApp
  post '/' do
    parsed_form_data = request.POST
    # ...
  end
end
```

but `request.POST` seems not to be very rack-app-ish. In standard rack the parsed form data is merged in params but I think a different method like `parsed_form_data` would be a better solution.

It would also be nice to have validations for form data, something like

``` ruby
desc 'example'
validate_form_data do
  required 'description', class: String, desc: 'example description'
end
post '/example' do
  desc = parsed_form_data['description']
  # ...
end
```

Did I miss something or is such functionality not (yet) implemented?

**Comment by adamluzsi** [comment]
Hello @janfri !
You are right , right now the wasn't user stories to start the validate_payload epic and because this , this functionality only have mindmap and a basic sketch level implementation for spiking , but nothing released at this point.

We thinking about the following singleton method

```ruby

.payload do
  unserialize do
    on "request content type here" do |payload|
       CustomUnserialize.parse(payload)
    end
    on "application/json" do |payload|
       JSON.parse(payload)
    end
  end

  validate do
    it_is_a Array, of: Hash do |element|
      element.has_a_key "foo", which_is_a: String
    end
  end

end
get "/baz" do
  payload #> [{"Foo" => "bar"}]
end

```

But it's an early concept, and we still in the process gathering user stories from our production use cases .

It would be great if you could provide example scenarios to us if you don't mind the time :)))

**Comment by janfri** [comment]
Payload may be complex so it could become epic indeed. ;-)

My current case is a very simple API in REST style. I need only _one_ simple param _message_ of type string with size between 1 and 30.

My current solution is something like:
```ruby
require 'rack/app'
require 'json'

class App < Rack::App

  def form_data
    case request.media_type
    when 'application/json'
      request.body.rewind
      JSON.parse(request.body.read)
    else
      request.POST
    end
  end

  def size_in_range? obj, range
    (obj.respond_to? :size) && (range === obj.size)
  end

  desc 'create a new event'
  post '/events' do
    msg = form_data['message']
    if size_in_range? msg, 1..30
      # create event
      'New event created'
    else
      # do error handling
      response.status = 400
      'no valid message given'
    end
  end

end

run App
```
So I can send the data URL-encoded, FORM-DATA-encoded or JSON-encoded:
```sh
$ curl -X POST -d message=foo http://localhost:9292/events
New event created
curl -X POST -F message=foo http://localhost:9292/events
New event created
$ curl -H "Content-Type: application/json" -X POST -d '{"message": "foo"}' http://localhost:9292/events
New event created
```

**Comment by adamluzsi** [comment]
Awesome ! I think we should provide something that doesn't include custom dsl but something that is easy to understand and generic. 

I start working on your request, as soon as the formats epic gets done. :)

**Comment by adamluzsi** [comment]
okey, all the stuff from the team backlog went out, 
today after work I start to work on your request @janfri  : )))))

**Comment by janfri** [comment]
Great news. :-)

**Comment by adamluzsi** [comment]
I split up your epic into two part.

one for the payload parsing based on content_type,
and one for the validating the parsed payload with a middleware.

For the first, what do you think, should it be go under the "payload" and "payload_stream" method as a dynamic object that is behave based on the content type unserialization, or there should be a new method, something like "parsed_payload" and "parsed_payload_stream" ?

**Comment by adamluzsi** [comment]
( @janfri )

**Comment by janfri** [comment]
> split up your epic into two part.
>
>one for the payload parsing based on content_type,
and one for the validating the parsed payload with a middleware.

Sounds reasonable.

>For the first, what do you think, should it be go under the "payload" and "payload_stream" method as a dynamic object that is behave based on the content type unserialization, or there should be a new method, something like "parsed_payload" and "parsed_payload_stream" ?

Maybe both?
- For simple cases methods like `parsed_payload` or `parsed_payload_stream` would be comfortable. Uses cases could be simple deserializers for JSON and XML.
- For strange things maybe an IO object would be useful? (I', not sure!) A use case could be to "parse" an uploded media-file with [mini_exiftool](https://github.com/janfri/mini_exiftool) to get metadata for further work with the media-file.

Just my 2 cents. Maybe others have better ideas?

**Comment by adamluzsi** [comment]
I talked about this with @BlasiusVonSzerencsi who use actively in production, and he mentioned, that it would be awesome if the :payload method would be dynamic based on the content_type, and there would be a :raw_payload for those, who want work explicitly with the string content of the payload.

**Comment by janfri** [comment]
> the :payload method would be dynamic based on the content_type, and there would be a :raw_payload for those, who want work explicitly with the string content of the payload.
Accepted.

What should be the reaction to a request with an unsupported content_type? Should there be a HTTP 415 response? Or should `payload` then have the unparsed content?

**Comment by adamluzsi** [comment]
The default behavior is the raw string . 
So the already made specs won't break.
Anything that make pre requirement should go to validate_payload block , so it can be processed into documentation as well.
The payload method it self should not do any validation , and only serve as a data input in the controller. 

That's the current direction if you like it. :)))

I already started to design the validate_payload method that almost alike with the validated_params syntax.

**Comment by adamluzsi** [comment]
Hello @janfri, sorry for not taking care of your issue, my daughter born and life was busy with this in these days. <3

I soon start to work on your request as soon as I can. 

Best regards 
Adam L.

**Comment by janfri** [comment]
I'll be patient. ;-)

**Comment by adamluzsi** [comment]
You are such an amazing person, thank you very much! :)

**Comment by adamluzsi** [comment]
Hy @janfri , little change in the future implementation. Yesterday, I talked about your feature request with my friends, and they suggested, that I should implement this as a middleware (which was in the original plan to), and as a core extension that can be used. In this way, we don't break the rolling release, and make this optional for those who require. 

Any opinion? 

```ruby
require 'rack/app'

class App < Rack::App

  apply_extension :payload 

  desc 'health check endpoint'
  validate_payload do |payload| 
    assert_instance_of Array, payload, "payload must be in bulk format"
    payload.each{|e| assert_instance_of(Hash, payload, "payload elements must be objects") }
  end 
  get '/' do
    payload #> is an object based on the 
  end

  get '/hello' do
    return 'Hello World'
  end

end
```

**Comment by adamluzsi** [comment]
```bash
rack-app 5.7.0 built to pkg/rack-app-5.7.0.gem.
Tagged v5.7.0.
Pushed git commits and tags.
Pushed rack-app 5.7.0 to rubygems.org.
```

**Comment by adamluzsi** [comment]
Validation will be out in v5.8.0, with minitest like validation block

**Comment by adamluzsi** [comment]
I Still think about the Validation. Is it really required ? 
I Can't find any use case to drive this part now.

For Example, all the use case I found, were using a custom Error handler block + a class that validate the payload based on restful params. 
And it is kind of idiomatic from the Rack and the middleware use mechanism.


```ruby
class App < Rack::App 
  
  get "/" do
    CustomValidation.new(payload)
    payload
  end

  error CustomValidationError do |ex| 
    response.status = 400 
    response.write(ex.message)
    finish!
  end 

end 
    
```
