### ISSUE TITLE
Namespace bug with numerical + dot formats (ex: /api/v1.0.0)

### ISSUE THREAD

**Issue by JoWilfrid** [rack-app/rack-app#17]
Hello,

I've noticed an issue with namespace after updating to version 5.11.0 from 5.10.2:

You can actually define this kind of URLs: `/api/v1/anything` but not this kind anymore: `/api/v1.0.0/anything`.

The "magical" thing is that even if `/api/v1.0.0/anything` doesn't work, `/api/v1.0/anything` works for a reason I don't know.

A sample app with the problem described and technical details is available here: https://github.com/JoWilfrid/rack-app-namespace-bug

Thank you.

**Comment by adamluzsi** [comment]
Hello @JoWilfrid !

Thank you for the issue report! 
I know the reason , the routing system now split any "extname" from the path and build different leafs. I move this logic from the node to the routing tree leaf building thanks to your use case.

It would take a day to find time integrate your use case to the behavior tests and write the fix so it will never ever happens again!

Please be patient a little while I resolve this issue, I try my best to find free time today.

**Comment by adamluzsi** [comment]
So the following use cases required?

  * /api/v1.0.0/ 
  * /api/v1.0.0/anything
  * /api/v1.0.0/anything/plus_more...

**Comment by JoWilfrid** [comment]
Hello @adamluzsi,

Thank you for your answer and reactivity.

As I just locked the `rack-app` version to `5.10.2`, it's not vital for me to have this correct in the day, so don't put too much pression on yourself :)

For the use cases, I would add `/v1.0.0/` and `/v1.0.0/anything`. For instance if I have an API host like `https://api.myservice.tld`, I will not necessary add `/api/` before the version number.
In fact, we can resume it as following:

* /anything/v1.0.0/anything where `anything` is optional and can represent 1 or more elements.

**Comment by adamluzsi** [comment]
Good point! I extend the use cases like that! :)
And by the way! You are awesome for creating and sending me feedback! 

I creating laptop stickers and when they are ready I send you one for this! ^~^

**Comment by JoWilfrid** [comment]
Oh yeah, thank you in advance :)

**Comment by adamluzsi** [comment]
Hello @JoWilfrid , I would like to ask for a little more patient, I got the solution to fix, and make the routing even more clean, but due to my limited time now (my daughter born "recently"), I have little times to continue the fix. But I'm on it! : )

**Comment by JoWilfrid** [comment]
@adamluzsi once again, no stress !
As said in a previous message, locking `rack-app` to version `5.10.2` is acceptable for me.
Nothing urgent here ;)

**Comment by adamluzsi** [comment]
Thank you! :) 
I fixed in my local repo this bad behavior, but got an inspiration , how fix it in a stylish way

**Comment by adamluzsi** [comment]
Hy @JoWilfrid ! :)

I'm ready, and released the new version where the routing had been remade to include explicit support for your usecase! 
[Here is the specification that I used](https://github.com/rack-app/rack-app/blob/master/spec/rack/app/router/versioned_path_spec.rb)

Please confirm, that your application now works perfectly with the newest version.

**Comment by JoWilfrid** [comment]
Everything seems good! 

I'm not sure it changes a lot but in order to be sure to cover a maximum of use cases, I would change paths var as following:


```ruby
paths = [
    '/1.0.0',
    '/v1.0.0',
    '/api/v1.0.0',
    '/api/version/1.0.0',
    '/api/v1.0.0/anything',
    '/api/version/1.0.0/anything',
    '/api/v1.0.0/anything/plus_more',
    '/api/version/1.0.0/anything/plus_more'
  ].freeze
```

**Comment by adamluzsi** [comment]
I added the test cases :)

**Comment by adamluzsi** [comment]
Thanks again for the help @JoWilfrid ! ^~^
