### ISSUE TITLE
restfull params

### ISSUE THREAD

**Issue by rastasi** [rack-app/rack-app#20]
I need an restfull_params helper, if it's possible

**Comment by adamluzsi** [comment]
Of course it's possible. It's already stored in an env variable, but until now, there wasn't any use story to create a public api/method for that value. 

I open up the query_string_params values too, so you can seperate the two value type if you need it.

methods: 
 * path_segments_params
 * query_string_params

**Comment by adamluzsi** [comment]
@janfri can I have an opinion from you too, you always have a good insight about stuffs like that. :)

**Comment by adamluzsi** [comment]
@rastasi V6.1.0 released, the specified methods added to the core helper methods.
you can check out the specification for [path segment params](https://github.com/rack-app/rack-app/blob/master/spec/rack/app/params/path_segment_params_spec.rb) and [query string params](https://github.com/rack-app/rack-app/blob/master/spec/rack/app/params/query_string_paths_spec.rb) too!

 If anything more required please don't hesitate to mention! :)
