### ISSUE TITLE
param_group

### ISSUE THREAD

**Issue by rastasi** [rack-app/rack-app#21]
I need an param_group options, like the apipie... for the create and update params for example ;)

**Comment by adamluzsi** [comment]
so you need something like 

```ruby
class App < Rack::App 

  params do 
    group :user do
      required 'id', :class => Integer, :desc => "user id'', :example => 123
    end
  end

  validate_params do 
    use :user 
    required 'test', :class => String, :desc => "test string'', :example => "hello world!"
  end 
  get '/:id' do 
     # ...
  end

end
```

**Comment by adamluzsi** [comment]
I feel this is easily achievable by creating a lambda where you create validation configuration and than fire it in the validation block passing the validator builder (self in that scope).

```ruby
class App < Rack::App 
    
  userParams = ->builder do
     builder.required 'id', :class => Integer, :desc => "user id'', :example => 123
  end

  validate_params do 
    userParams.call(self)
    required 'test', :class => String, :desc => "test string'', :example => "hello world!"
  end 
  get '/:id' do 
     # ...
  end

end
```

I didn't test this out but my guess this will work like charm.

The reason why I don't want to implement this is, it's not clear how should the class behave in different scenarios such us inheritance, and this would decrease simplicity. 

But it's an awesome idea and probably worth an extension later on. :)
