### ISSUE TITLE
Make project more welcoming by changing the illustrations

### ISSUE THREAD

**Issue by timriley** [rack-app/rack-app#3]
I'm really interested in your work, but I can't help but think the big illustration of the woman on your README and homepage makes the project less welcoming to a wide range of potential users and contributors.

Would you by any chance consider removing these illustrations or replacing them with something else? Thank you for your consideration!

**Comment by adamluzsi** [comment]
@timriley We started to think about the new logo, any idea is welcome right now! 
We didn't want offense anyone with this, our designer made with the following idea:
"Miss Ruby sitting on a rack, and helping the developers to create something awesome"

As soon as possible, I try to remove the logo from most of the places, and one of my friend started to think about a new logo, that could be awesome. My first idea was a platypus, but the others say, it has no meaning... :( 

Cheers, Adam.

**Comment by adamluzsi** [comment]
For anyone who has a good logo idea, please contribute the project by simply share it with us!
Just write it here and I forward to the artist guy! : )

**Comment by timriley** [comment]
Thanks for the positive response, @adamluzsi! I think a friendly-looking animal, instead of a representation of any sort of man or woman, would certainly help make the project more appealing to a wider audience. I'd love to see your artist try a platypus :)

**Comment by adamluzsi** [comment]
Or maybe an Onion? 
Because request are go into middleware "layers", and Onion is layered too.

**Comment by adamluzsi** [comment]
Nah... that sounds stupid... : /

**Comment by szenti** [comment]
@timriley I wonder how a picture of a man or a woman would make any project less welcoming for potential users and/or contributors. Would you care to elaborate?

**Comment by cpg** [comment]
@szenti May want to look at a common urban use of the word [rack](http://www.urbandictionary.com/define.php?term=rack). I felt it was not very offensive at all.

**Comment by szenti** [comment]
@cpg thank you for the clarification.

**Comment by thilonel** [comment]
I love the logo. Please don't change it.

**Comment by adamluzsi** [comment]
We thinking about keeping Miss ruby as a symbol for the language, 
and try to find a cute animal or something, as her pet to represent the project. :) 
So nobody would be sad.

But that's just an idea, any opinions?

**Comment by timriley** [comment]
The problem with Miss Ruby is that you feature a woman in revealing clothing or in a sexy pose, both of which “objectify” her and make it seem like women would be less welcome in this project, because you don't value them as equal humans, but more like objects to be gazed upon. This is why I suggested that you remove the illustrations or change them altogether if you want to make your project welcoming to all. This is really important both for your project and for open source software in general.

**Comment by timriley** [comment]
One more thing. It would seem that your own Code of Conduct prohibits the type of imagery you're using:

> Examples of unacceptable behavior by participants include the use of sexual language or imagery.

**Comment by cpg** [comment]
Well, if you are going to keep Miss ruby and add a cute animal to the mix, there is only one answer here, ... a beaver. If that does not put things over the top ... :)

**Comment by timriley** [comment]
Gosh. This sort of puerile comment is exactly the kind of problematic behaviour encouraged by the current imagery, and exactly the kind of thing that will make people feel unwelcome and unsafe in this project's space.

@adamluzsi, I'd like to report [this comment](https://github.com/rack-app/rack-app/issues/3#issuecomment-243982246) to you, and hopefully you can delete it and make it clear that you don't tolerate sexual language, according to your code of conduct.

Hopefully this is also motivation to make the changes to the project's images sooner rather than later 😞

**Comment by cpg** [comment]
If @timriley is not capable of understanding that that comment (in no way sexual in nature) is *siding* on the idea of changing the logo to something less suggestive, then there are bigger issues with command of English language comprehension.

OTOH, the backhanded insult suggests there may have been in fact a decent command of the language. Idiotic puritan insults are just as out of order. An agreement that the was already over the top and it may have helped, in a positive way, yet an insult was chosen. Talk about problematic behaviour.

**Comment by timriley** [comment]
@cgp I'm sorry if I misunderstood you. To me it seemed you were implying that sexual innuendo is harmless and we shouldn't worry about it.

This is a problem with jokes in text-based discussion that broaches topics like this, and like you say, why a logo change would be good.

**Comment by cpg** [comment]
Notice this sarcastic part (and the smiley):

> If that does not put things over the top ... I don't know what will :)

Personally, I think it's best to steer away from this kind of imagery, as it can be considered over-the-top by a few. Users of this project may not be impacted (will likely never see the logo), however, some contributors may, and that is probably worth a change.

**Comment by adamluzsi** [comment]
Please don't fight with each other. First @timriley , I'm sorry but I can't remove anyones opinion in a discussion, and it's clear that @cpg never intended with it to be rude or anything. Actually by first impression I thought, he intended to lighten the mood in the discussion.

Okey everybody, let's try to be positive and find a solution together, by starting brainstorm on what can be the new logo, opposed to what can't be the logo.

Please @Soffny help us with your great drawing magic! : )

**Comment by adamluzsi** [comment]
to start the brainstorm flow, I put an idea in, and please before measure it's good or bad, put one idea in the issue too. 

Ideas for the new logo: 
  * A Transformer robot that opened out from the Rack logo into a Humanoid figure
  * Miss ruby with only a little feminine appearance
  * [A Koto](https://en.wikipedia.org/wiki/Koto_(instrument))
  * [A bullet train](http://japantravelmate.com/travel-tips-planning/shinkansen-photos-video)

**Comment by thilonel** [comment]
@timriley Oh just fucking get over it, please.

**Comment by adamluzsi** [comment]
Or a cat with flash lookimg tail

**Comment by Soffny** [comment]
hey guys, miss ruby's creator here. i'd like to say that i did not intend the drawing to be offensive in any way. i was given a general idea about her which i followed and didn't question it much how it would affect a bigger audience than just a couple of people. i'm no professional, still learning so i'll do better next time. 

i'll start thinking about a redesign of miss ruby and a pet for her, if there's no objection to the idea. personally i liked this the most. but i'd like to create something that most are happy with, so please, i encourage everyone to leave suggestions here and we'll see what kind of idea is the most popular. 

thank you for bringing this problem to our and my attention and hopefully we can find a solution together.

**Comment by Soffny** [comment]
or how's a ruby colored lego building?

**Comment by Soffny** [comment]
another idea: pet squirrel for miss ruby, or just the squirrel itself, maybe interacting with the lego building

**Comment by adamluzsi** [comment]
Squirrel is cute. And what do you think about a Quokka!

**Comment by adamluzsi** [comment]
But I guess it can be something abstract too.

**Comment by Soffny** [comment]
i just thought of a squirrel bc it's quick, clever and stacks stuff. Would a quokka make more sense with its traits and qualities to be the mascot?

**Comment by Soffny** [comment]
what wouod you guys think about a bit more cyber/sci-fi looking miss ruby? Would dress her less provocative, would give her hologram goggles or eyeshileds and put in some metallic elements in her clothes.

**Comment by stevenhaddox** [comment]
Skipped a lot of this because it's been 3 days since this issue was created and this logo still exists. Perhaps you could start by putting plain text until something better is created? If you truly care about the wrong message that the logo is sending, it should be yanked immediately. This is my strong opinion, and it is strongly held.

**Comment by stevenhaddox** [comment]
Okay, so there are a lot of ideas in here and I've caught up. Sorry for not being able to read through them all earlier. I absolutely love the idea of a Miss Ruby mascot as it is a part of Ruby culture and I think it's a great opportunity to help promote diversification within our community as something we respect and even view as a hero. That said, can I implore us to do the following as a community:

1. Remove any offensive, sexualizing, or objectifying imagery that currently exists (possibly even throughout the repository's history)
2. Work together to find a way to come up with a Miss Ruby who's respected, intelligent, and her own person.

I almost feel like that may have been part of the intent originally given to @soffny, but I wasn't involved so I can't claim any actual knowledge, and sadly some of the reactions with emojis that seem to mock comments sincerely trying to address this issue negate that perspective almost completely.

I think this is a rare opportunity for a project to admit when it's made a mistake, self-correct, and even turn the negative into a hopefully positive outcome.

**Comment by adamluzsi** [comment]
hello @stevenhaddox , and thank you for the friendly reminder. 
When this Issue created, I removed the picture immediately from the readme but totally forgot about the website, and I'm sorry about this. :( 

The whole Miss Ruby idea came from an [old youtube video where programming languages talked with each other](https://www.youtube.com/watch?v=GQRjWxfz-PQ). : )

**Comment by Soffny** [comment]
new miss ruby is in the works :)

**Comment by adamluzsi** [comment]
Miss @Soffny already made an awesome concept about the new Miss Ruby, 
soon there wil be some teaser! ^~^

**Comment by Soffny** [comment]
i'd like to ask everyone for some feedback on this miss ruby:
http://puu.sh/rhMAX/971bf3eddc.jpg
http://puu.sh/rhMBN/fb94ea9496.jpg

**Comment by adamluzsi** [comment]
@stevenhaddox @timriley  @cpg @szenti @BlasiusVonSzerencsi 
Any opinions? :)

**Comment by BlasiusVonSzerencsi** [comment]
The sketches are awesome in my opinion.

**Comment by BlasiusVonSzerencsi** [comment]
Although I'd also ask Heroku whether it's compliant with "what people expect of them". ;-)

**Comment by adamluzsi** [comment]
If no one has any more opinion,  I considerate this sketch accepted and ask miss @Soffny to go with this :)

**Comment by adamluzsi** [comment]
![2016-10-10](https://cloud.githubusercontent.com/assets/2897081/19233082/9b1f776e-8ee3-11e6-88c3-e4f8999f5358.png)

**Comment by stevenhaddox** [comment]
My life's been kind of hectic the past few weeks and I apologize for not getting back sooner. I love the changes you've made and really appreciate the responsiveness and adjustments to help make the project more friendly to everyone! Keep up the good work!

**Comment by adamluzsi** [comment]
Thank you @stevenhaddox for the reply , your response mean a lot to the rack-app team! :)

**Comment by adamluzsi** [comment]
Hy all, little update, @Soffny working hard on the new website logo, please be patient a little, until it's done. :)

**Comment by Soffny** [comment]
**new ms ruby, ready to launch!**

![ruby](https://cloud.githubusercontent.com/assets/17203415/22184842/6d76dad4-e0da-11e6-8276-451f888dd081.png)

**Comment by adamluzsi** [comment]
If the new logo match everybody's requirements, that I close this issue with miss @Soffny 's  new Logo. :) 

Thank you everyone for helping us with this!
Especially @timriley for pointing out this, @cpg, @stevenhaddox and @BlasiusVonSzerencsi for stay to the end and helping.
