### ISSUE TITLE
Unexpected behavior of request param parsing

### ISSUE THREAD

**Issue by aindenko** [rack-app/rack-app#31]
Hi, we've found bug in framework behaviour.
When you do request with FQDN inside URL path, framework silently cuts last domain part.
F.e.
 GET http://mysite.com/api/example.com will result 
 to params["fqdn"] = "example" and expected is params["fqdn"] = "example.com".

Bug appears only when domain name is the last param. So for example: 
F.e.
 GET http://mysite.com/api/example.com/12345 will result 
 to params["fqdn"] = "example.com" and expected is params["fqdn"] = "example.com".

**Comment by aindenko** [comment]
@adamluzsi  ?  :)

**Comment by adamluzsi** [comment]
Sorry for the late answer, I missed the notification!

Hmm, my guess that it's because the extension in the end of the path matched to a unserialization block , and if it's not given , it fall back to a default. I make a test with this today at night :)

**Comment by adamluzsi** [comment]
So, first of all, I would like to thank you @aindenko for opening this issue. 
It means a lot that you put effort and time to examine and communicate this issue with me!

I made a new specification for this case: 
```ruby

  describe '#params' do

    require 'yaml'

    rack_app do
      # ...
      get '/domain/:addr' do
        YAML.dump(params)
      end
      # ...
    end

    let(:request) { {:url => '/params', :env => {}} }

    subject { YAML.load(get(request).body) }

    # ... 
    context 'when query string given in request env' do
        # ...

        context 'and the dynamic path part include dot' do
          before { request[:url]= '/domain/example.com' }

          context 'and that "extension" has no unserializer defined' do
            it { is_expected.to eq({"addr" => 'example.com'}) }
          end


        end
    end
end
``` 


Please verify that the new version of rack-app is works as how you expected.
Thank you for your patience and happy coding! :)

Kind regards,
@adamluzsi

**Comment by adamluzsi** [comment]
@aindenko ? :)

**Comment by aindenko** [comment]
Thx @adamluzsi for the new release and all the effort in developing such a great project :+1:
I confirm, updating to the 7.5.2  version fixed the issue.

Thx again and have a great day :)

**Comment by adamluzsi** [comment]
I already have a great day if I was able to help you @aindenko ! :)
