### ISSUE TITLE
What happened to the website?

### ISSUE THREAD

**Issue by v3rmin** [rack-app/rack-app#32]
<img width="1209" alt="rack-app" src="https://user-images.githubusercontent.com/799089/47198105-b6b35400-d36a-11e8-8bf3-f7dbe3429408.png">

*Follow-up question:* Is this project still active?

**Comment by adamluzsi** [comment]
Dear @v3rmin,

I'm truly sorry for the inconvenience, I relocated to a new country, and my old bank card expired, and I didn't see the Auto-Renew fail message, and I also failed to allocate time to fix it in time.
I need to fix my workflow regarding this. Thank you very much for letting me know this, and I fixed it now ASAP! :S 

Could you confirm, that the website is working correctly for you as well ?

Kind regards,
Adam L.

**Comment by dukex** [comment]
Thanks @adamluzsi to make website live again, I'm using a lot the rack-app rigth now

**Comment by adamluzsi** [comment]
You are much welcome @dukex! 
If you don't mind tell me some feedback what is your personal experience! :)))

**Comment by adamluzsi** [comment]
Since the object of this issue is resolved, I'm closing it

**Comment by adamluzsi** [comment]
Sadly, I have some kind of problem with my whois settings, my support ticket is pending currently.

**Comment by adamluzsi** [comment]
It's settled now, web page is available again
