### ISSUE TITLE
RSpec warnings

### ISSUE THREAD

**Issue by qortex** [rack-app/rack-app#35]
Cosmetic warnings, but still they show up when running RSpec on my project with warnings enabled:
```sh
/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-app-7.6.1/lib/rack/app/payload/parser/builder/formats.rb:79: warning: mismatched indentations at 'end' with 'else' at 75
/home/mic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-app-7.6.1/lib/rack/app/streamer/scheduler/null.rb:7: warning: mismatched indentations at 'end' with 'def' at 5
```

**Comment by adamluzsi** [comment]
Hi @qortex, 

I will look into this and fix it!
Thank you very much for opening this issue! 

Cheers,
Adam

**Comment by adamluzsi** [comment]
Hi @qortex,

Could you please confirm that from version `7.6.2` the rspec warning issue you have is gone?

Cheers,
Adam

**Comment by qortex** [comment]
Hi,
Yes, I confirm they're gone.
Karma has gone up!

Thanks for the quick fix

**Comment by adamluzsi** [comment]
I'm happy that I solved your issue!
De rien
