### ISSUE TITLE
Error handler for mounted app

### ISSUE THREAD

**Issue by qortex** [rack-app/rack-app#38]
Error handlers work fine for exception raised inside the app.

But when an exception is raised in a mounted app, the error handler of the parent app is not called.

Is there a way to get this behaviour, or is it a feature request?

**Comment by adamluzsi** [comment]
Hi @qortex! :)
To me, up until now, the error handling was only meant to be interpreted in the local class scope.
I don't say, I'm against the idea, just until now, I didn't really have serious need to introduce cascading style based error handling when the rack-app class mounts other rack-based applications.

The approach I did was to create middleware, test it firmly and explain in the spec that this will meant to handle multiple types of errors, and then use this middleware where it makes sense. It was KISS enough for me, so I didn't extend the core logic of the framework with it.

I generally try to handle errors as close to the source as possible, which usually the interactor or the external resource implementation, and try to keep error handling low in the external interface layer like in the rack-app classes.

If you want to try out the middleware approach, you can find the rack-app spec about middlewares and mounting logic here: [`spec/rack/app/middleware/mounted_app_spec.rb`](https://github.com/rack-app/rack-app/blob/master/spec/rack/app/middleware/mounted_app_spec.rb).

Else, if you see it would be more readable and testable to do with rack-app the error blocks, I'm happy to look through and discuss your use-cases and suggestions.

Cheers,
Adam

**Comment by qortex** [comment]
After spending a few days with my design, I agree my initial idea was actually not so clean.

I find it better to have error handling in the app itself, instead of introducing coupling between isolated rack apps.

What I ended up doing is provide the error capability through a `RackAppBase` class, that each of my rack app inherits from.

That way, it is clear where the capability comes from and doesn't rely on the rack app being in a certain environment.

What it allows me is to have a unified way of handling & formatting uncaught errors for my frontend to consume easily.

I'll close this, let me know if you think it should stay open!

**Comment by adamluzsi** [comment]
Man, @qortex I really the design  direction you just described! I might use the same in the future instead of the middleware approach! : )))

Je vous souhaite beaucoup de succès avec votre projet.
