### ISSUE TITLE
POST request without Content-Length header on WEBrick yields HTTP status code 411

### ISSUE THREAD

**Issue by romanvbabenko** [rack-app/rack-app#39]
### Post handler does not work

**Describe the bug**

Post handler does not work

**To Reproduce**

```
class App < Rack::App
  post '/users' do
  end
end
```

```
curl -v -X POST localhost:9292/users                                   ?7 13:41:05
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9292 (#0)
> POST /users HTTP/1.1
> Host: localhost:9292
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 411 Length Required
< Content-Type: text/html; charset=ISO-8859-1
< Server: WEBrick/1.6.0 (Ruby/2.7.1/2020-03-31)
< Date: Sun, 31 May 2020 10:41:14 GMT
< Content-Length: 303
< Connection: close
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Length Required</TITLE></HEAD>
  <BODY>
    <H1>Length Required</H1>
    WEBrick::HTTPStatus::LengthRequired
    <HR>
    <ADDRESS>
     WEBrick/1.6.0 (Ruby/2.7.1/2020-03-31) at
     localhost:9292
    </ADDRESS>
  </BODY>
</HTML>
* Closing connection 0
```

**Expected behavior**

Raise no error ```Length Required``

**ruby interpreter**

MRI

**ruby version**
2.7.1
**rack-app version**
rack-app (7.6.4)
**Additional context**
Add more examples with other no just GET methods

**Comment by adamluzsi** [comment]
Hi @romanvbabenko ,

Thank you so much for opening this issue.

The error you experiencing is related to webrick.
In case you send a POST request, the webrick implementation expects the `Content-Length` header presence.

If you wish to keep using webrick and curl, here is some example to set `Content-Length` for your request:
* explicit: `curl -X POST http://localhost:9292/ -H 'Content-Length: 0'`
* implicit: `curl -X POST http://localhost:9292/ -d ''`

I hope this helps to unblock your progress!
I wish you good health and happy programming!

Cheers,
Adam L

**Comment by adamluzsi** [comment]
Please @romanvbabenko, leave feedback about whether or not I was able to assist you with your issue.
If you have more questions, please don't hesitate to ask, I'm happy to help! :)

Cheers,
Adam L.

**Comment by adamluzsi** [comment]
@romanvbabenko, can I help you more with this case? :)
I would like to close the issue if you no longer have a blocker on this.

Cheers,
Adam L.

**Comment by adamluzsi** [comment]
Hi @romanvbabenko,

I close this ticket as I believe you received the help you needed with your issue.

Cheers and Happy coding! :)
