### ISSUE TITLE
How to serve static assets with Rack::App?

### ISSUE THREAD

**Issue by momolog** [rack-app/rack-app#43]
I am trying to make Rack::App serve static files from the folder `public/` (like possible with Sinatra using `set :public_folder, 'public'`). 

Is this supported out of the box? If not, how to do it in the simplest way?

**Comment by adamluzsi** [comment]
Hi @momolog !

Thank you for your question, here's an example how to do achieve your goal:

```ruby
class MediaFileServer < Rack::App

  serve_files_from '/folder/from/project/root', to: '/files'

  # or from a controller
  get '/' do
    serve_file 'custom_file_path_to_stream_back'
  end
  
end
```

**Comment by adamluzsi** [comment]
@momolog , does this example answers your question?

**Comment by adamluzsi** [comment]
@momolog was I able to answer your question?
