### ISSUE TITLE
  params  is  empty {}  when  send form to   post "/hello"  

### ISSUE THREAD

**Issue by tablecell** [rack-app/rack-app#44]
**Describe the bug**

**To Reproduce**
1. test.rb
 
```
require "rack/app"

class App < Rack::App
  desc "some hello endpoint"
  get "/hello" do
    '<!doctype html><html><head></head><body><form  action="/hello" method="post" ><input name="username" ><button>Send</button></form></body></html>'
  end

  desc "post hello endpoint"
  post "/hello" do
    params["username"]
  end
end
```

2.  config.ru
```
require './test'
run App
```
rackup 
3.  visit http://localhost:9292/hello
    fill form 
4.  click send button
post    params is  empty {}

**Expected behavior**

**ruby interpreter**
ruby interpreter implementation like Mruby, Jruby, ...

**ruby version**
ruby 2.6.6p146
**rack-app version**

**Additional context**

**Comment by adamluzsi** [comment]
Dear @tablecell ,

Thank you very much for reaching out to me, I'm super happy about it! ^~^

In rack-app the value sent as http body (payload) and then value sent as query string values are not mixed together for various reasons. In POST, the form data is sent as request payload. 

It is an intentional design decision in rack-app that the API must described explicitly instead of implicitly what data is taken from where.

Here is an example:
```ruby
require 'rack/app'
class App < Rack::App

  payload do
    parser do
      accept :json, :www_form_urlencoded
      reject_unsupported_media_types  
    end
  end

  post '/' do
    payload #> is an object based on the parser output for the given request content type
  end

end
```

Let me know if this answers your question.

Cheers
Adam

**Comment by adamluzsi** [comment]
I accidentally clicked on the lock, then unlock button, sorry I'm from mobile and partially still asleep. :S

**Comment by adamluzsi** [comment]
Here you can find more examples:

http://www.rack-app.com/examples/payload

**Comment by tablecell** [comment]
payload  can  solve  problem  about post   params.

btw  why rack-app design is  so complex  even more than rails ?
if upload file   form   enctype="multipart/form-data" how can paload parse ?
Is there any example  about upload file   ?

**Comment by adamluzsi** [comment]
rack-app follows imperative programming style, and in an app , what you need must be explicitly defined. This reduce the required mental model to know what's happening in your application external interface layer. It also reduce security concerns with things doing too much, without the awareness of the code owners. This approach makes the framework both painfully minimalist and highly flexible. For example you are not limited to a set of predefined format. Heck, If your project needs a binary format based serialization, you can just use that, and so on.

For your issue, Rack::Multipart should allow you parse the request env.

If you wish, I can add Multipart support to the default payload parsers. We just didn't had the use-case yet as we mainly working with JSON.

In the example section, there is an example about defining payload parsers for content types.

I'm sorry for not being much help to you at the moment. :(

If you wish, we can move forward together and make the multipart support. :)
