### ISSUE TITLE
serializer block is not executed on http_status! responses

### ISSUE THREAD

**Issue by thilonel** [rack-app/rack-app#47]
`http_status! 404, { errors: ["couldn't find record with #{params["id"]}"] }`
This is serialized with `to_s` even if a serializer block like
`serializer { |obj| obj.is_a?(String) ? obj : JSON.dump(obj) }` is defined

**Comment by adamluzsi** [comment]
I've just released rack-app version 11.0.0 on rubygems.org. 
Could you take a moment to see if it works for your needs?

Here are the specific tests that cover this use case:
https://github.com/rack-app/rack-app/blob/master/spec/rack/app/http_status_spec.rb#L47-L67

**Comment by thilonel** [comment]
Awesome, thank you!
