### ISSUE TITLE
Rack::App logo does not represent what's expected of Heroku

### ISSUE THREAD

**Issue by stevenhaddox** [rack-app/rack-app#5]
http://www.rack-app.com is displaying an [incredibly offensive image](http://www.rack-app.com/img/logo_v2.png) featuring the word "app" across a woman's chest.

Can you please fix this? I expect more of Rubyists and more of Heroku and can't express my disappointment. Surely you could be more creative than to resort to this as a logo of your hard work.

**Comment by stevenhaddox** [comment]
Closing as issue #3 already addresses this and was opened 3 days ago.

**Comment by Palver** [comment]
> I expect more of Rubyists and more of Heroku and can't express my disappointment. 

Are you frustrated?
