### ISSUE TITLE
Make `request.params` behave similarly as the `params` method

### ISSUE THREAD

**Issue by adamluzsi** [rack-app/rack-app#51]
Dear Contributors,

For an apparent reference on the Rack's request object, you can view it [here][rack-request].

This feature request was prompted by [the following feedback](https://github.com/rack-app/rack-app-front_end/issues/6).

Currently, the `request` object available within the endpoint block scope is an instance of [Rack::Request][rack-request].

[Rack::Request][rack-request] in Ruby's Rack library provides a foundational interface for incoming HTTP requests, encapsulating the raw HTTP data in an intuitive, object-oriented format.

Frameworks such as rack-app, Sinatra, or Rails introduce a more intricate layer with path parameters, rooted in the RESTful API design concept that transforms URL path segments into parameters.

While [Rack::Request][rack-request] manages raw HTTP data without deducing the URL structure or routing, higher-level frameworks built on Rack introduce path parameters.

A discrepancy arises when `params` and `request.params` return different values. 

Though our preference for the minimalist approach using the core [Rack::Request][rack-request] kept things uncomplicated, it appears to have led to an unclear API concerning parameters in this context.

To address this, we plan to roll out a Rack::App::Request. This will align the parameter accessors with the endpoint scope:
- **path_segments_params**: Parameters present solely in your path segments.
- **query_string_params**: Parameters found only in your query string.
- **validated_params**: Parameters that have passed your validation, ensuring protection against hash key-value-based injections.
- **params**: This will return:
  - `validated_params` if validation is specified.
  - Otherwise, it will consolidate all parameter types into a hash map for retrieval.

Thank you for your continued collaboration and understanding.

[rack-request]: https://github.com/rack/rack/blob/main/lib/rack/request.rb

**Comment by adamluzsi** [comment]
https://github.com/rack-app/rack-app-front_end/issues/6

**Comment by vidtreonou** [comment]
@adamluzsi. This captures the problem well. The main issue being that  you have to know where to look  for different params.

If we can to the point where I an confidently look one place may that be params collection or the request.params that would be great.

In my somewhat naive attempt to solve the problem ,  I was thinking that since all the methods  (path_segments_params, query_string_params and validated_params) all return hashes that I could merge them behind the scenes . 

I soon ran into issues when there is a duplicate parameter name.

I look forward to see what solution you come up with but if I can help in anyway let me know.

**Comment by adamluzsi** [comment]
In the meantime, while I'm working on the updates, you might find it useful to check out the `merged_params` method. 🙌

**Comment by adamluzsi** [comment]
@vidtreonou, I've released rack-app v10 on rubygems.org, featuring the new request object type with params functionality. I'd appreciate your feedback on it. Could you let me know if it matches your expectations?

**Comment by vidtreonou** [comment]
Way cool! I will look at it now

**Comment by vidtreonou** [comment]
Based on the code in the https://github.com/rack-app/rack-app-front_end/issues/6.

<img width="901" alt="Screenshot 2023-09-12 at 04 58 21" src="https://github.com/rack-app/rack-app/assets/141216207/dda229d5-9443-4bd4-ab67-762a2129445e">


when I update the gem to 10.0.0.

<img width="901" alt="Screenshot 2023-09-12 at 04 56 02" src="https://github.com/rack-app/rack-app/assets/141216207/5bd09151-32dd-4c0c-a480-dd0127a890b8">

when I run the app I get this error

<img width="901" alt="Screenshot 2023-09-12 at 04 56 19" src="https://github.com/rack-app/rack-app/assets/141216207/6a256be2-062a-410d-8516-e8c7479be790">


I pulled dow the latest version of rack-app/rack-app and ran the tests and all was green.

if I down grade back to 9.0.0 I get

<img width="901" alt="9 0 0 output" src="https://github.com/rack-app/rack-app/assets/141216207/52b359c0-f573-4a40-a19b-573d4431aec2">

**Comment by vidtreonou** [comment]
hope this helps , shout if you need any more information.

**Comment by adamluzsi** [comment]
This is actually related to rack-app/front_end rather than rack-app. 
It's an interesting observation. It seems when `Rack::App::VERSION` is set to "10.0.0", it's interpreted as being "less" than "3.0.0" because it starts with a 1. If I'm not mistaken, I made this oversight back in 2016. It's a reminder that one shouldn't compare versions as strings when they represent integers.

**Comment by adamluzsi** [comment]
I initially implemented this version check-based logic in rack-app/front_end to determine if the extension feature was available in rack-app core, as it was introduced in v3. I've decided to remove this guard block from the front-end code in the next release. It's unlikely anyone is using a 7-year-old version of rack-app, and if they are, it's high time for an upgrade. 😄

**Comment by adamluzsi** [comment]
You've presented the examples and outlined the issue brilliantly.
If you're open to suggestions, I have a few markdown techniques I favor when sharing examples on GitHub. 
You might find them helpful, or perhaps you're already familiar with them.

# For Code examples

Using the three backtick to leave code examples:

````markdown
```ruby
puts "my example ruby code"
```
````

->

```ruby
puts "my example ruby code"
```

It makes the code easy to read as it won't depend on picture quality, plus it can be copy pasted easily.

# For backtraces

In GitHub-flavored Markdown, you can create collapsible content using the `<details>` and `<summary>` HTML tags. 
If you want to include code blocks (like backtraces) within the collapsible content. 

Here's an example of how you can create a collapsible block that contains a backtrace:

````markdown
<details>
  <summary>Click to expand the backtrace</summary>

  ```
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  NameError: name 'example' is not defined
  ```

</details>
````

->

<details>
  <summary>Click to expand the backtrace</summary>

  ```
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  NameError: name 'example' is not defined
  ```

</details>

**Comment by adamluzsi** [comment]
Please upgrade to rack-app-front_end version 0.22.2. 
Following this update, the `front_end` extension should function as anticipated.
[I've also made updates to the example app we used in our discussions.](https://github.com/rack-app/example-for-vidtreonou)

**Comment by vidtreonou** [comment]
I am always open to suggestion when it come this stuff, I was struggling with formatting hence the images .  but will give these a go. 

I will update the front end and let you know. thanks for the explanation.

**Comment by adamluzsi** [comment]
If it's causing any inconvenience, feel free to continue with screenshots. I truly appreciate the extra effort you put into including them in the issues! Thank you, @vidtreonou!

**Comment by vidtreonou** [comment]
Ok sorry for the delay getting back,

When using the following Gemfile:

```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rack-app" , "9.0.0"
gem "rack-app-front_end", "0.22.1"

gem "puma", "~> 6.3"
gem "pry-remote", "~> 0.1.8"
```


I get the following output:

<img width="1471" alt="Screenshot 2023-09-13 at 00 27 01" src="https://github.com/rack-app/rack-app/assets/141216207/52dc052e-58f5-43b4-af43-d9f8a328e878">


however when using 

```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rack-app" , "10.0.0"
gem "rack-app-front_end", "0.22.2"

gem "puma", "~> 6.3"
gem "pry-remote", "~> 0.1.8"
```

I get the following output

<img width="869" alt="Screenshot 2023-09-13 at 00 25 19" src="https://github.com/rack-app/rack-app/assets/141216207/b986db21-875f-47d9-b0cd-257e0fc8d9c2">

from wha I am observing version 10.0.0 is not capturing  the Post parameters in the request.params.

**Comment by vidtreonou** [comment]
hope this helps

**Comment by vidtreonou** [comment]
for context.

this the form I am using

```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <form action="/customers/1?qp=1" method="post">
        <input type="text" name="test">
        <input type="submit" value="Go  ">
    </form>
    
</body>
</html> 
```

and this is the server

```
require 'rack/app'
require 'rack/app/front_end'
require 'pry-remote'

class App < Rack::App
  apply_extensions :front_end
  apply_extensions :logger

  get '/' do
    render "index.html.erb"
  end

  middlewares do |b|
    b.use Rack::ContentLength
  end

  get '/:greeting' do
    logger.info "request.params -> #{request.params}" 
    logger.info "params -> #{params}" 
    puts config
    "ok"
  end

  post '/customers/:id' do
    logger.info "path_segments_params -> #{path_segments_params}" 
    logger.info "query_string_params -> #{query_string_params}" 
    logger.info "request.params -> #{request.params}" 
    logger.info "params -> #{params}" 
    "ok"
  end

end

run App
```

**Comment by adamluzsi** [comment]
@dekubu, would you mind testing the latest version of rack-app (11.0.2)? It's updated to retain the original Rack::Request params method behavior, especially for Post request Form payload parsing.

**Comment by dekubu** [comment]
Sure can ! , will update when done 
Delaney Burke
Founder

***@***.***
+372 533 22 524
vidtreon.com <http://vidtreon.com>




On September 14, 2023, GitHub ***@***.***> wrote:
> @dekubu <https://github.com/dekubu>, would you mind testing the latest
> version of rack-app (11.0.2)? It's updated to retain the original
> Rack::Request params method behavior, especially for Post request Form
> payload parsing.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/rack-app/rack-app/issues/51#issuecomment-
1720060810>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/BBVMTTZ7G3625BJVULSQS5TX2NOZPANCNFSM6AAAAAA4RUX6DI>.
You are receiving this because you were mentioned.Message ID: <rack-
***@***.***>

**Comment by dekubu** [comment]
I have ran code with the update and I get the expected result

![Screenshot 2023-09-15 at 13 42 04](https://github.com/rack-app/rack-app/assets/141216207/acffeed9-ed6e-4524-9da1-d740f352e8bb)

all parameters are in the request.params collection.

So this working perfectly !!! 🎉

**Comment by dekubu** [comment]
Ok so I also ran this code

![Screenshot 2023-09-15 at 13 49 46](https://github.com/rack-app/rack-app/assets/141216207/72d596b3-578c-4a35-b31f-ea8bc8416ecc)

I removed   support for front_end extension.

I got this output

![Screenshot 2023-09-15 at 13 46 24](https://github.com/rack-app/rack-app/assets/141216207/3443b805-bd05-444c-9257-5b89d1b997cd)


As you can see the values do not appear in the params collection,

can you please confirm if this is by design.

thanks again for the help.

**Comment by adamluzsi** [comment]
Indeed, by design, `params` only encompasses URL path-related parameters, like segment parameters and query parameters. For request payload content, you can access it through either `payload` or `request.params`.

**Comment by dekubu** [comment]
Boomooom! I see my mistake now. I got it into my head that request.params was only available to me if front_end extensions was enabled!

everything works perfectly thanks.

**Comment by adamluzsi** [comment]
The FrontEnd extension provides:

- The `render` instance method to render a view template with a given input data
- Singleton methods related to template handling (e.g., `layout "layout.erb.html"`)
- A mechanism to define template helpers.

**Comment by adamluzsi** [comment]
If any aspect of this issue is still pending or you need further assistance, please let me know. 
Otherwise, do you feel it has been satisfactorily resolved?

**Comment by dekubu** [comment]
I have updated the latest changes into my project and we are good to go and this has indeed been resolved.
thanks again,
