### ISSUE TITLE
What is the best way to bundle views in an extension?

### ISSUE THREAD

**Issue by dekubu** [rack-app/rack-app#54]
```
Rack::App::Extension.register(:example) do
  get 'greeting' do
      render 'greeting.html.erb'
  end
end

```

Given the example extension above, I want to package the is extension in a gem.
what would be the best way to bundle the greeting.html.erb with extension?

I have looked at the documentation , worker  and sequel extensions for inspiration but I have not found an example which bundles views.

I am thinking of adding the views to the gem and using hooks to  copy them into place, but this does not sound very minimalistic. 

@adamluzsi What would you suggest?

**Comment by adamluzsi** [comment]
I am intrigued to learn more about your choice to utilize the rack-app extension. Understanding your specific use case will provide a clearer picture. The rack-app extension is indeed a solid tool for enhancing rack-app functionalities. However, it's primarily designed for creating extensions within the framework itself.

Considering the scenario you've described, a more straightforward solution might be more suitable. You might consider creating a gem encompassing a module with constants or singleton methods. These could return the path of the view files contained within the gem. Given Ruby's nature as an interpreted language, having all project dependencies installed on the host system is a prerequisite, making utilizing the views directly from the gem practical.

```ruby
module MyViewGem
  MY_VIEW_NAME = File.join(File.dirname(__FILE__), 'greeting.html.erb')
end
```

You can place your views directly within the gem and utilize the full path from your constants by passing them to the `render` method.

**Comment by adamluzsi** [comment]
This method helps you steer clear of vendor lock-in, and its framework-agnostic nature allows for easy reuse across different frameworks, as it doesn't contain any framework-specific content.

**Comment by dekubu** [comment]
Hey @adamluzsi thanks for the speedy reply.

Ok to clarify usage pattern, In  the previous issue I was using Onmiauth, I have got all that working now and I have implemented sign in with apple and google.

I have extracted this functionality into a SSO  (social sign on )  Extension.
this extension is a mixture  routes and views so I wanted a simple way to package that to make it reusable. so that I can have

```
class Play < Rack::App
    
    apply_extensions :logger
    apply_extensions :front_end
    apply_extensions :sso
.......
```


From you explanation above , I think I might be using the extension functionality more like rails engine and it not really designed that way, correct?

**Comment by dekubu** [comment]
On a side note I do like this

```
module MyViewGem
  MY_VIEW_NAME = File.join(File.dirname(__FILE__), 'greeting.html.erb')
end
````

I can see how I could use this approach to share views across multiple apps! pretty cool

**Comment by dekubu** [comment]
I have resolved this issue. so thanks again for the help.

**Comment by adamluzsi** [comment]
Hi @dekubu,

Apologies for the delayed response.

Upon further thinking about this scenario, I've come to believe that the gem could also just incorporate a rack interface-compliant class that can be configured or constructed with the necessary parameters for omniauth. 
In this scenario, the choice of framework becomes irrelevant; it could be rack-app, but this approach allows freedom from vendor lock-in, enabling easy experimentation to find the most maintenance-friendly solution with omniauth.

Anyways, I'm glad you resolved the issue and weren't blocked on this. 

Cheers,
Adam
